import React from 'react';
import { Timeperiod } from '../../api/types';
export declare const AaDoraChart: ({ timeperiod, charts, chartColor, customOptions, customPointFormatter, yAxisType, yAxisFormat, yAxisFormatter, chartHeight, loading, className, yAxisTitle, customOpacity, isMarker, isStacking, setUpdate, update, }: {
    timeperiod: Timeperiod;
    charts: any;
    chartColor?: any;
    customOptions?: any;
    customPointFormatter?: any;
    yAxisType?: any;
    yAxisFormat?: string;
    yAxisFormatter?: any;
    chartHeight?: number;
    loading?: boolean;
    className?: string;
    yAxisTitle?: string;
    customOpacity?: number;
    isMarker?: boolean;
    isStacking?: boolean;
    setUpdate?: React.Dispatch<React.SetStateAction<number>> | null;
    update?: number;
}) => React.JSX.Element;
